### PR TITLE
Upgraded eftest fixes #70

### LINKED ISSUE #70: Upgrade eftest
`eftest 0.5.0` is available

### PR DESCRIPTION
**Pull request by LukasRychtecky**

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks, but can you ensure your commit message is consistent with the repository? So something more like:

    Upgrade Eftest in template (fixes #70)

**Comment by LukasRychtecky** [comment]
Sure, my fault. So format like `Upgrade Eftest in template (fixes #70)` is OK?

**Comment by weavejester** [comment]
Yes; I follow the [seven rules](https://chris.beams.io/posts/git-commit/#seven-rules) for my commit messages.

**Comment by LukasRychtecky** [comment]
I'll be more careful next time. Thx.

**Comment by LukasRychtecky** [comment]
FYI I've fixed the commit message.

**Comment by weavejester** [comment]
Your commit message says "Upgraded" instead of "Upgrade". Can you fix that?

**Comment by LukasRychtecky** [comment]
Done. I see "5. Use the imperative mood".

**Comment by LukasRychtecky** [comment]
Could you merge it? Thanks

**Comment by weavejester** [comment]
Sure. Sorry for taking so long. This slipped off my todo list.

**Pull request merged**
